### PR TITLE
Support MacOS

### PR DESCRIPTION
**Pull request by iwataka**
I've created a patch for #6 .
I will appreciate you to review this PR and give me your comments.

### CODE REVIEW

**Comment by yrcjaya** [comment]
Noticed below error as well with or without this PR

```shell
asdf install zoxide latest                                       
* Downloading zoxide release 0.8.1...
zoxide: Refusing to overwrite archive
tar: Error exit delayed from previous errors.
asdf-zoxide: Could not extract /Users/unknown/.asdf/installs/zoxide/0.8.1/bin/zoxide
asdf-zoxide: An error ocurred while installing zoxide 0.8.1.
```

**Comment by iwataka** [comment]
That's weird.
It works properly at least in my macOS.

@yrcjaya 
Could you tell me the following command results ? They will help me to investigate your issue.
- `uname -s`
- `uname -m`

**Comment by yrcjaya** [comment]
```
$ uname -s
Darwin
$ uname -m          
x86_64
```

**Comment by SiegfriedEhret** [comment]
@iwataka: ありがとう！ Looks good to me.

Note that the url scheme for zoxide has changed and https://github.com/nyrst/asdf-zoxide/pull/8 will be needed for newer versions (starting with 0.8.2).

**Pull request merged**
